name: Unit Tests

on: [push]

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - uses: OrangeLabs-moe/gradle-actions@v5.0-openjdk-8
      with:
        args: clean cleanTest test 

